[phases.setup]
nixPkgs = ["python311", "ollama"]

[phases.install]
cmds = [
  "python3 -m ensurepip",
  "python3 -m pip install --upgrade pip",
  "python3 -m pip install -r requirements.txt"
]

[start]
cmd = "ollama serve & sleep 5 && streamlit run emne.py --server.port=8501 --server.address=0.0.0.0"
